randomizer/urls.py
from django.urls import path

from . import views

app_name = 'randomizer'

urlpatterns = [
    # Main
    path('', views.AboutView.as_view(), name='home'),
    path('randomize', views.RandomizeView.as_view(), name='randomize'),

    # Help
    path('how-to-play', views.HowToPlayView.as_view(), name='how-to-play'),
    path('difficulties', views.AboutView.as_view(), name='difficulties'),
    path('options', views.OptionsView.as_view(), name='options'),
    path('resources', views.ResourcesView.as_view(), name='resources'),
    path('guide', views.GuideView.as_view(), name='guide'),
    path('updates', views.UpdatesView.as_view(), name='updates'),

    # Generation
    path('seed', views.GenerateView.as_view(), name='generate'),
    path('h/<slug:hash>', views.HashView.as_view(), name='patch-from-hash'),
    path('hash/<slug:hash>/<slug:region>', views.GenerateFromHashView.as_view(), name='generate-from-hash'),
    path('pack', views.PackingView.as_view(), name='pack'),

    # API
    path('api/v1/generate', views.APIGenerateView.as_view(), name='api-v1-generate'),
    path('api/v1/flags', views.APIFlags.as_view(), name='api-v1-flags'),
]

zora_web/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('randomizer.urls')),
]

randomizer/models.py
from django.db import models
from jsonfield import JSONField


class Seed(models.Model):
    hash = models.CharField(max_length=1000, unique=True)
    seed = models.BigIntegerField()
    version = models.CharField(max_length=16)
    generated = models.DateTimeField(auto_now_add=True)
    mode = models.CharField(max_length=16)
    debug_mode = models.BooleanField(default=False)
    flags = models.TextField(default='')
    file_select_char = models.CharField(max_length=100, default='')
    file_select_hash = models.CharField(max_length=100, default='')
    race_mode = models.BooleanField(default=False)
    spoiler = JSONField(default={})


class Patch(models.Model):
    seed = models.ForeignKey(Seed, on_delete=models.CASCADE)
    region = models.CharField(max_length=8)
    sha1 = models.CharField(max_length=40)
    patch = models.TextField()

    class Meta:
        unique_together = [
            ('seed', 'region'),
        ]

randomizer/forms.py
from django import forms

MODES = (
    ('standard', 'Standard'),
    ('itemonly', 'Item Only'),
)


class GenerateForm(forms.Form):
    seed = forms.Field(required=False)
    mode = forms.ChoiceField(required=False, choices=MODES, initial='open')
    flags = forms.Field(required=False, initial='')
    debug_mode = forms.BooleanField(required=False, initial=False)
    race_mode = forms.BooleanField(required=False, initial=False)

randomizer/views.py
import binascii
import hashlib
import json
import logging
import os
import random
import string
import tempfile
import shutil

from django.conf import settings
from django.db import transaction
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse, HttpResponseNotFound, QueryDict
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, FormView

from .models import Seed, Patch
from .forms import GenerateForm
from .logic.flags import CATEGORIES, PRESETS, FlagError
from .logic.main import ZoraRandomizer, VERSION
from .logic.patch import PatchJSONEncoder
from .logic.settings import Settings

# Get an instance of a logger
logger = logging.getLogger(__name__)


def _build_flag_json_data(flag, parent_modes=None):
    """

    Args:
        flag (randomizer.logic.flags.Flag): Flag class to build JSON data for.
        parent_modes (list[str]): Modes of the parent flag to restrict the child to.

    Returns:
        dict: Flag data.

    """
    modes = flag.modes.copy()
    if parent_modes is not None:
        modes = list(set(modes) & set(parent_modes))

    d = {
        'value': flag.value,
        'modes': modes,
        'choices': [],
        'options': [],
    }
    for choice in flag.choices:
        d['choices'].append(_build_flag_json_data(choice, parent_modes=modes))
    for option in flag.options:
        d['options'].append(_build_flag_json_data(option, parent_modes=modes))

    return d


# Build JSON representation of flag hierarchy.
FLAGS = []
for category in CATEGORIES:
    for flag in category.flags:
        FLAGS.append(_build_flag_json_data(flag))


class RandomizerView(TemplateView):
    """
    Base class for views that generate a ROM, i.e. randomizer and patch-from-hash views.
    This gets common context data.
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = VERSION
        context['debug_enabled'] = settings.DEBUG
#        context['beta_site'] = settings.BETA
        context['categories'] = CATEGORIES
        context['presets'] = PRESETS
        context['flags'] = FLAGS

        return context


class AboutView(RandomizerView):
    template_name = 'randomizer/about.html'


class HowToPlayView(RandomizerView):
    template_name = 'randomizer/how_to_play.html'


class OptionsView(RandomizerView):
    template_name = 'randomizer/options.html'


class ResourcesView(RandomizerView):
    template_name = 'randomizer/resources.html'


class GuideView(RandomizerView):
    template_name = 'randomizer/guide.html'


class UpdatesView(RandomizerView):
    template_name = 'randomizer/updates.html'


class RandomizeView(RandomizerView):
    template_name = 'randomizer/randomize.html'


class HashView(RandomizerView):
    template_name = 'randomizer/patch_from_hash.html'


class GenerateView(FormView):
    form_class = GenerateForm
    return_patch_data = True

    def form_valid(self, form):
        data = form.cleaned_data

        # Debug mode is only allowed if the server is running in debug mode for development.
        if not settings.DEBUG:
            data['debug_mode'] = False

        # If seed is provided, use it.  Otherwise generate a random seed (10 digits max).
        # For non-numeric values, take the CRC32 checksum of it.
        seed = data['seed']
        if seed:
            if seed.isdigit():
                seed = int(seed)
                if seed < 1 or seed > 0xFFFFFFFF:
                    seed = None
            else:
                seed = binascii.crc32(seed.encode())

        # If seed is not provided, generate a 32 bit seed integer using the CSPRNG.
        if not seed:
            r = random.SystemRandom()
            seed = r.getrandbits(32)
            del r

        mode = data['mode'] or 'open'
        debug_mode = bool(data['debug_mode'])
        race_mode = bool(data['race_mode'])

        # Build game world, randomize it, and generate the patch.
        randomizer = ZoraRandomizer(Settings(seed, data['flags'] or '', mode, debug_mode))

        try:
            print("Randomize()")
            randomizer.Randomize()
            print("GetPatch()")
            patches = {'US': randomizer.GetPatch()}
        except FlagError as e:
            # Catch error with flags and return that error message instead.
            result = {
                'error': e.args[0],
            }
            return JsonResponse(result, encoder=PatchJSONEncoder)
        except Exception:
            logger.error("ERROR form data: {!r}, generated seed: {!r}".format(data, seed))
            raise
        print("making result")
        # Send back patch data.
        result = {
            'logic': VERSION,
            'seed': seed,
            'hash': "hash", #world.hash,
            'mode': mode,
            'debug_mode': debug_mode,
            'flag_string': randomizer.settings.flag_string,
            'file_select_character': "character", # world.file_select_character,
            'file_select_hash': "file_select_hash", # world.file_select_hash,
            'permalink': reverse('randomizer:patch-from-hash', kwargs={'hash': "hash"}),# world.hash}),
            'race_mode': race_mode,
            'spoiler': {} #world.spoiler if not race_mode else {},
        }

        # Save patch to the database (don't need to save EU since it's the same as US).
        """with transaction.atomic():
            # If there's an existing seed with the same hash, replace it.
            try:
                s = Seed.objects.get(hash="hash") #world.hash)
            except Seed.DoesNotExist:
                pass
            else:
                s.delete()

            #s = Seed(hash=world.hash, seed=seed, version=VERSION, mode=mode, debug_mode=debug_mode,
            #         flags=world.settings.flag_string, file_select_char=world.file_select_character,
            #         file_select_hash=world.file_select_hash, race_mode=race_mode, spoiler=world.spoiler)
            s = Seed(hash="hash", seed=seed, version=VERSION, mode=mode, debug_mode=debug_mode,
                     flags=randomizer.settings.flag_string, file_select_char="ignore-this",
                     file_select_hash="TODO: add hash here", race_mode=race_mode, spoiler={})
            s.save()

            for region, patch in patches.items():
                patch_dump = json.dumps(patch, cls=PatchJSONEncoder)
                h = hashlib.sha1()
                h.update(patch_dump.encode())
                p = Patch(seed=s, region=region, sha1=h.hexdigest(), patch=patch_dump)
                p.save()
        """
        # Check if we're including the patch data in the response.
        if self.return_patch_data:
            result['patch'] = patches['US']  # Patch for EU version is the same as US.
        
        print("response")

        return JsonResponse(result, encoder=PatchJSONEncoder)

    def form_invalid(self, form):
        msg = "{} form error: ".format(self.__class__.__name__) + '; '.join(form.errors)
        logger.error(msg)
        return HttpResponseBadRequest(msg.encode())

    def get(self, request, *args, **kwargs):
        """Handle GET requests: return 400 error."""
        msg = "{} GET method not allowed".format(self.__class__.__name__)
        logger.error(msg)
        return HttpResponseBadRequest(msg.encode())


class GenerateFromHashView(View):
    @staticmethod
    def get(request, hash, region):
        """Get a previously generated patch via hash value."""
        # EU patch is actually the US one.
        if region == 'EU':
            region = 'US'

        try:
            s = Seed.objects.get(hash=hash)
        except Seed.DoesNotExist:
            return HttpResponseNotFound("No record for hash {0!r}".format(hash))

        try:
            p = Patch.objects.get(seed=s, region=region)
        except Patch.DoesNotExist:
            return HttpResponseNotFound("No patch found for hash {0!r}, region {1!r}".format(hash, region))

        result = {
            'logic': s.version,
            'seed': s.seed,
            'hash': s.hash,
            'mode': s.mode,
            'debug_mode': s.debug_mode,
            'flag_string': s.flags,
            'file_select_character': s.file_select_char,
            'file_select_hash': s.file_select_hash,
            'patch': json.loads(p.patch),
            'race_mode': s.race_mode,
            'spoiler': s.spoiler,
        }
        return JsonResponse(result)


@method_decorator(csrf_exempt, name='dispatch')
class PackingView(View):
    @staticmethod
    def post(request):
        """Pack uploaded ROM into the provided WAD file as downloaded file."""
        if not request.FILES.get('rom'):
            return HttpResponseBadRequest("ROM file not provided")
        elif not request.FILES.get('wad'):
            return HttpResponseBadRequest("WAD file not provided")

        with tempfile.TemporaryDirectory() as dumpdir:
            romfile = os.path.join(dumpdir, 'rom.sfc')
            with open(romfile, 'wb') as f:
                shutil.copyfileobj(request.FILES['rom'], f)

            # Compress ROM file for US and EU (not JP)
            rom_to_copy = romfile
            #if request.POST.get('region') in ('US', 'EU'):
            #    romcompressed = os.path.join(dumpdir, 'rom_compressed.sfc')
            #    nlzss.encode_file(romfile, romcompressed)
            #    rom_to_copy = romcompressed

            # Dump WAD file
            #wadf = Wii.WAD.load(request.FILES['wad'].read())
            #wadf.dumpDir(dumpdir)

            # Dump U8 archive
            #u8file = os.path.join(dumpdir, '00000005.app')
            #u8unpackdir = u8file + '_unpacked'
            #u8archive = Wii.U8.loadFile(u8file)
            #u8archive.dumpDir(u8unpackdir)

            # Copy randomized ROM over

randomizer/templates/randomizer/layouts/default.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Standard HTML5 meta tags -->
    <meta name="author" content="Dorkmaster Flek">
    <meta name="description" content="Experience a non-linear open world version of the classic NES game!">
    <meta name="keywords" content="Legend of Zelda, Z1, Z1R, speedrun, speedrunning, randomizer, rando, openworld, open world, zora">

    <!-- Open Graph meta tags -->
    <meta property="og:title" content="Zelda One Randomizer for All"/>
    <meta property="og:description" content="Experience a non-linear open world version of the classic Legend of Zelda NES game!"/>
    <meta property="og:type" content="website"/>
    <!-- <meta property="og:url" content="https://randomizer.smrpgspeedruns.com"/>
    <meta property="og:image" content="https://randomizer.smrpgspeedruns.com{% static "randomizer/img/twitter_profile.png" %}"/> -->

    <!-- Twitter meta tags 
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@SMRPGRandomizer">
    <meta name="twitter:creator" content="@DorkmasterFlek">
    <meta name="twitter:title" content="Super Mario RPG Open World Randomizer">
    <meta name="twitter:description" content="Experience a non-linear open world version of the classic SNES game!">
    <meta name="twitter:image" content="https://randomizer.smrpgspeedruns.com{% static "randomizer/img/twitter_profile.png" %}"> -->

    <title>
        {% if beta_site %}
            *BETA*
        {% endif %}
        Zelda One Randomizer for All
    </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'randomizer/img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="{% static "randomizer/css/jquery.json-viewer.css" %}">
    <link rel="stylesheet" href="{% static "randomizer/css/main.css" %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/localforage/1.7.1/localforage.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spark-md5/3.0.0/spark-md5.min.js"></script>
    <script src="{% static "randomizer/js/jquery.json-viewer.js" %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <!-- Logo -->
    <a class="navbar-brand" href="{% url 'randomizer:home' %}"><img src="{% static 'randomizer/img/zelda-logo.png' %}" alt="Zelda One Randomizer for All"/></a>

    <ul class="navbar-nav">
        <!-- Links -->
        <li class="nav-item {% if 'randomize' in request.path %}active{% endif %}">
            <a class="nav-link" href="{% url 'randomizer:randomize' %}">Generate Randomized Game</a>
        </li>
        <li class="nav-item {% if 'resources' in request.path %}active{% endif %}">
            <a class="nav-link" href="{% url 'randomizer:resources' %}">Discord</a>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Help</a>
            <div class="dropdown-menu dropdown-menu-right">
                <!-- <a class="dropdown-item {% if 'how-to-play' in request.path %}active{% endif %}" href="{% url 'randomizer:how-to-play' %}">How To Play</a> -->
                <a class="dropdown-item {% if 'options' in request.path %}active{% endif %}" href="{% url 'randomizer:options' %}">Flag & Mode Explanations</a>
                <!-- <a class="dropdown-item {% if 'guide' in request.path %}active{% endif %}" href="{% url 'randomizer:guide' %}">Player's Guide</a>-->
                <a class="dropdown-item {% if 'updates' in request.path %}active{% endif %}" href="{% url 'randomizer:updates' %}">Version History</a>
                <a class="dropdown-item" href="https://github.com/tetraly/zora/issues/new" target="_blank">Report an Issue</a>
            </div>
        </li>
    </ul>
</nav>
<div class="clearfix mt-3"></div>
{% if beta_site %}
    <div class="alert alert-danger text-center" role="alert">
        <div>
            <span class="fas fa-flask"></span>
            WARNING: THIS IS THE BETA SITE!
            <span class="fas fa-flask"></span>
        </div>
        <div>
            Everything here is for testing and will probably break at some point!  If you're looking for the current
            stable version, <a href="https://randomizer.smrpgspeedruns.com">go here</a>!
        </div>
    </div>
{% endif %}
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>